FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /training_service

COPY pyproject.toml uv.lock* ./

RUN uv sync --frozen --no-dev --group training-pipeline

COPY services/training_service/src ./src/
COPY services/training_service/config ./config/
COPY services/feature_store_service/config ./services/feature_store_service/config/

RUN mkdir -p ./data/raw \
            ./data/processed \
            ./models \
            ./metrics \
            ./logs

ENV PYTHONPATH=/training_service

CMD ["uv", "run", "-m", "src.train"]