project: anomaly_detection
registry: /feature_store_service/data/registry/registry.db
provider: local

online_store:
  type: redis
  connection_string: "redis:6379"
  key_ttl_seconds: 86400 

offline_store:
  type: file

entity_key_serialization_version: 3