# Redis Configuration for MLOps Online Store
# ==========================================

# Persistence: Snapshot every 60s if 1+ key changed
save 60 1
# Append Only File: Better durability
appendonly yes
appendfilename "appendonly.aof"

# Memory Management (Protect host from OOM)
maxmemory 512mb
maxmemory-policy allkeys-lru

# Networking
port 6379
bind 0.0.0.0

# Directory for persistence data
dir /data
