FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Set environment variables:
# 1. Prevent Python from writing .pyc files to disk
# 2. Ensure logs are sent straight to terminal (unbuffered)
# 3. Allow 'uv' to install packages directly into the system Python
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_SYSTEM_PYTHON=1

WORKDIR /feature_store_service

# Install C++ build tools (build-essential) required for compiling certain Python libraries (e.g., Pandas, Feast).
# Clean up apt cache afterwards to minimize image size.
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy dependency definition files to the working directory
COPY services/feature_store_service/pyproject.toml services/feature_store_service/uv.lock ./

RUN uv sync --frozen 

# Create necessary folders for the Feast Registry (metadata) and Offline Store (Parquet files).
COPY services/feature_store_service/src feature_store_service/src/

WORKDIR /feature_store_service/src
